#ifndef LTM_CORBACTIVESERVICE_IDL
#define LTM_CORBACTIVESERVICE_IDL

#include "LTMTopicDetails.idl"

#if defined(__TAO_IDL)

# pragma prefix "dst.defence.gov.au"

module ltm {

    const string CORBActiveService_OID = "LTM_CORBActiveService";

    interface CORBActiveService
    {
        long    pushTopic(in LTMTopicDetails td);
    };

}; // ltm

# endif

#endif // LTM_CORBACTIVESERVICE_IDL
