/***************************************************************
    Copyright 2016, 2017 Defence Science and Technology Group,
    Department of Defence,
    Australian Government

	This file is part of LASAGNE.

    LASAGNE is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as
    published by the Free Software Foundation, either version 3
    of the License, or (at your option) any later version.

    LASAGNE is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public
    License along with LASAGNE.  If not, see <http://www.gnu.org/licenses/>.
***************************************************************/
#ifndef TAF_ENTITYDESCRIPTOR_IDL
#define TAF_ENTITYDESCRIPTOR_IDL

#include "taf/BasicTypes.idl"

#pragma prefix "dsto.defence.gov.au"

module taf
{
# pragma version taf 1.0

    struct LOADTime {
        unsigned long long sec; unsigned long usec;
    };

    struct EntityDescriptor {
        string      ident_;
        string      libpathname_;
        string      objectclass_;
        string      parameters_;
        string      info_;
        Object      obj_;
        LOADTime    loadTime_;
        unsigned short flags_;
    };

    enum SVC_Flags {
      SVC_EXECUTE, SVC_STATIC, SVC_DYNAMIC, SVC_OBJECT, SVC_MODULE, SVC_STREAM, SVC_ACTIVE, SVC_FINIED
    };

    typedef sequence<EntityDescriptor>  EntityDescriptorSeq;
}; // taf

#endif
