#ifndef COMMON_201771_151619LASAGNE_TAFSupport
#define COMMON_201771_151619LASAGNE_TAFSupport


/******************************************************
* Code generated by LASAGNE IDL Compiler
* LASAGNE BE Version : 1.4.4
* TAO_IDL FE Version : 2.4.3
* LASAGNE Build Time : Jul  1 2017
* Generation Visitor : LASAGNE_TAFSupport
* Creation Date      : 201771_151619
* Input File         : common.idl
******************************************************/


#if defined(TAF_USES_DDSCORBA)


#include "commonC.h"
#include "commonS.h"

#elif defined(TAF_USES_NDDS)

#include "common.h"

#elif defined(TAF_USES_COREDX)

#include "common.hh"

#elif defined(TAF_USES_OPENSPLICE)

#include "ccpp_common.h"

#endif

#if defined(TAF_USES_OPENDDS)

#include "commonTypeSupportC.h"
#include "commonTypeSupportS.h"
#include "commonTypeSupportImpl.h"

#elif defined(TAF_USES_NDDS)

#include "commonSupport.h"
#include "commonPlugin.h"

#elif defined(TAF_USES_COREDX)

#include "commonTypeSupport.hh"
#include "commonDataReader.hh"
#include "commonDataWriter.hh"

#elif defined(TAF_USES_OPENSPLICE)


#if defined(TAF_USES_DDSCORBA)

#include "commonDcpsC.h"

#else

#include "commonDcps.h"

#endif
#include "commonDcps_Impl.h"

#else
#error ERROR : You have not set TAF DDS flags for your build

#endif


#include "dds/DDSPubSub.h"


namespace common
{
   typedef DEFINE_DDS_TYPESUPPORT(common, tester) tester_DataSupport;
   //typedef tester_DataSupport::_data_holder_typetester_HolderType
   typedef tester_DataSupport::_data_type    tester_TopicType;
   typedef tester_DataSupport::_data_type    tester_CORBAType;
   typedef tester_DataSupport::_data_type    tester_TopicAdapter;
   typedef tester_DataSupport::_data_type    tester_CORBAAdapter;

   typedef class TAFDDS::TOPICReaderListener< tester_DataSupport > tester_DataListener; 
   typedef class TAFDDS::DDS_Subscriber< TAFDDS::SubscriberListener > tester_Subscriber;
   typedef class TAFDDS::DDS_Publisher< TAFDDS::PublisherListener > tester_Publisher;
   typedef class TAFDDS::DDS_Topic< tester_DataSupport > tester_Topic;
   typedef class TAFDDS::DDS_Reader< tester_Topic, tester_DataListener > tester_Reader;
   typedef class TAFDDS::DDS_Writer< tester_DataSupport > tester_Writer;

} // namespace common

#endif //COMMON_201771_151619LASAGNE_TAFSupport
