#ifndef TEST_201771_151620LASAGNE_TAFSupport
#define TEST_201771_151620LASAGNE_TAFSupport


/******************************************************
* Code generated by LASAGNE IDL Compiler
* LASAGNE BE Version : 1.4.4
* TAO_IDL FE Version : 2.4.3
* LASAGNE Build Time : Jul  1 2017
* Generation Visitor : LASAGNE_TAFSupport
* Creation Date      : 201771_151620
* Input File         : Test.idl
******************************************************/

// IDL Includes 1
#include "commonTAFSupport.h" // common.idl

#if defined(TAF_USES_DDSCORBA)


#include "TestC.h"
#include "TestS.h"

#elif defined(TAF_USES_NDDS)

#include "Test.h"

#elif defined(TAF_USES_COREDX)

#include "Test.hh"

#elif defined(TAF_USES_OPENSPLICE)

#include "ccpp_Test.h"

#endif

#if defined(TAF_USES_OPENDDS)

#include "TestTypeSupportC.h"
#include "TestTypeSupportS.h"
#include "TestTypeSupportImpl.h"

#elif defined(TAF_USES_NDDS)

#include "TestSupport.h"
#include "TestPlugin.h"

#elif defined(TAF_USES_COREDX)

#include "TestTypeSupport.hh"
#include "TestDataReader.hh"
#include "TestDataWriter.hh"

#elif defined(TAF_USES_OPENSPLICE)


#if defined(TAF_USES_DDSCORBA)

#include "TestDcpsC.h"

#else

#include "TestDcps.h"

#endif
#include "TestDcps_Impl.h"

#else
#error ERROR : You have not set TAF DDS flags for your build

#endif


#include "dds/DDSPubSub.h"


namespace dsto
{
   typedef DEFINE_DDS_TYPESUPPORT(dsto, DRAWDetails) DRAWDetails_DataSupport;
   //typedef DRAWDetails_DataSupport::_data_holder_typeDRAWDetails_HolderType
   typedef DRAWDetails_DataSupport::_data_type    DRAWDetails_TopicType;
   typedef DRAWDetails_DataSupport::_data_type    DRAWDetails_CORBAType;
   typedef DRAWDetails_DataSupport::_data_type    DRAWDetails_TopicAdapter;
   typedef DRAWDetails_DataSupport::_data_type    DRAWDetails_CORBAAdapter;

   typedef class TAFDDS::TOPICReaderListener< DRAWDetails_DataSupport > DRAWDetails_DataListener; 
   typedef class TAFDDS::DDS_Subscriber< TAFDDS::SubscriberListener > DRAWDetails_Subscriber;
   typedef class TAFDDS::DDS_Publisher< TAFDDS::PublisherListener > DRAWDetails_Publisher;
   typedef class TAFDDS::DDS_Topic< DRAWDetails_DataSupport > DRAWDetails_Topic;
   typedef class TAFDDS::DDS_Reader< DRAWDetails_Topic, DRAWDetails_DataListener > DRAWDetails_Reader;
   typedef class TAFDDS::DDS_Writer< DRAWDetails_DataSupport > DRAWDetails_Writer;

} // namespace dsto

#endif //TEST_201771_151620LASAGNE_TAFSupport
